"""change contact model

Revision ID: 2f07de6f3433
Revises: 11f70e5bc432
Create Date: 2023-08-20 19:52:22.594836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f07de6f3433'
down_revision: Union[str, None] = '11f70e5bc432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contacts_personal_phone_key', 'contacts', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('contacts_personal_phone_key', 'contacts', ['personal_phone'])
    # ### end Alembic commands ###
